# Generated by Django 4.2.1 on 2023-05-19 22:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TheKiddoDontist', '0002_review_doctor'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Doctor',
        ),
    ]
